name: osuwin21-web

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6767:6767"
    restart: unless-stopped
    networks:
      - stack_network   

networks:
  stack_network:
    external: true
    name: banchopy_default # Assuming using bancho.py stack